import { Globe, Zap, BookOpen, Shield, Users, Target, Mail } from "lucide-react";
import SEOHead from "@/components/SEOHead";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import ScrollToTop from "@/components/ScrollToTop";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { useLanguage } from "@/contexts/LanguageContext";

export default function About() {
  const { t, lang } = useLanguage();

  const features = {
    ar: [
      { icon: <Zap className="h-5 w-5 text-primary" />, title: "أخبار فورية", desc: "تحديث تلقائي كل 15 دقيقة من أكثر من 20 مصدراً إخبارياً موثوقاً." },
      { icon: <BookOpen className="h-5 w-5 text-primary" />, title: "ملخصات ذكية", desc: "ملخص يومي شامل مُولَّد بالذكاء الاصطناعي يُغطي أبرز أحداث اليوم." },
      { icon: <Globe className="h-5 w-5 text-primary" />, title: "تغطية متعددة اللغات", desc: "أخبار عربية وسويدية وعالمية مع إمكانية الترجمة الفورية." },
      { icon: <Shield className="h-5 w-5 text-primary" />, title: "مصادر موثوقة", desc: "نختار مصادرنا بعناية لضمان دقة المعلومة وموثوقيتها." },
      { icon: <Users className="h-5 w-5 text-primary" />, title: "مجتمع القراء", desc: "إنشاء حساب شخصي لحفظ الأخبار المفضلة وتنظيمها في مجلدات." },
      { icon: <Target className="h-5 w-5 text-primary" />, title: "تخصيص المحتوى", desc: "فلترة الأخبار حسب الفئة والمصدر والتاريخ لتجربة مخصصة." },
    ],
    en: [
      { icon: <Zap className="h-5 w-5 text-primary" />, title: "Real-time News", desc: "Automatic updates every 15 minutes from over 20 trusted news sources." },
      { icon: <BookOpen className="h-5 w-5 text-primary" />, title: "Smart Summaries", desc: "Comprehensive daily summaries generated by AI covering the day's top events." },
      { icon: <Globe className="h-5 w-5 text-primary" />, title: "Multilingual Coverage", desc: "Arabic, Swedish, and international news with instant translation." },
      { icon: <Shield className="h-5 w-5 text-primary" />, title: "Trusted Sources", desc: "We carefully select our sources to ensure accuracy and reliability." },
      { icon: <Users className="h-5 w-5 text-primary" />, title: "Reader Community", desc: "Create a personal account to save favorite news and organize them in folders." },
      { icon: <Target className="h-5 w-5 text-primary" />, title: "Content Personalization", desc: "Filter news by category, source, and date for a personalized experience." },
    ],
    sv: [
      { icon: <Zap className="h-5 w-5 text-primary" />, title: "Realtidsnyheter", desc: "Automatisk uppdatering var 15:e minut från över 20 betrodda nyhetskällor." },
      { icon: <BookOpen className="h-5 w-5 text-primary" />, title: "Smarta sammanfattningar", desc: "Heltäckande dagliga sammanfattningar genererade av AI." },
      { icon: <Globe className="h-5 w-5 text-primary" />, title: "Flerspråkig täckning", desc: "Arabiska, svenska och internationella nyheter med direktöversättning." },
      { icon: <Shield className="h-5 w-5 text-primary" />, title: "Betrodda källor", desc: "Vi väljer noggrant våra källor för att säkerställa noggrannhet." },
      { icon: <Users className="h-5 w-5 text-primary" />, title: "Läsargemenskap", desc: "Skapa ett personligt konto för att spara favoritnyheter." },
      { icon: <Target className="h-5 w-5 text-primary" />, title: "Innehållsanpassning", desc: "Filtrera nyheter efter kategori, källa och datum." },
    ],
  };

  const stats = {
    ar: [
      { value: "20+", label: "مصدر إخباري" },
      { value: "200+", label: "زيارة يومية" },
      { value: "24/7", label: "تحديث مستمر" },
      { value: "3", label: "لغات متاحة" },
    ],
    en: [
      { value: "20+", label: "News Sources" },
      { value: "200+", label: "Daily Visitors" },
      { value: "24/7", label: "Continuous Updates" },
      { value: "3", label: "Languages" },
    ],
    sv: [
      { value: "20+", label: "Nyhetskällor" },
      { value: "200+", label: "Dagliga besökare" },
      { value: "24/7", label: "Kontinuerliga uppdateringar" },
      { value: "3", label: "Språk" },
    ],
  };

  const heroTexts = {
    ar: {
      badge: "عن الموقع",
      title: "عربي سمارت للأخبار",
      subtitle: "منصة إخبارية ذكية تجمع أهم الأخبار العربية والسويدية والعالمية في مكان واحد، مع ملخصات يومية مُولَّدة بالذكاء الاصطناعي.",
      missionTitle: "رسالتنا",
      missionP1: "أُسِّس موقع عربي سمارت للأخبار بهدف تقديم تجربة إخبارية متكاملة للجالية العربية في السويد والعالم. نؤمن بأن المعلومة الصحيحة في الوقت المناسب هي حق لكل إنسان.",
      missionP2: "نجمع الأخبار من أكثر من 20 مصدراً موثوقاً، ونستخدم الذكاء الاصطناعي لتوليد ملخصات يومية دقيقة تُوفّر وقتك وتُبقيك على اطلاع دائم.",
      featuresTitle: "ما يميزنا",
      sourcesTitle: "مصادرنا الإخبارية",
      sourcesSubtitle: "نجمع الأخبار من أبرز المصادر الإخبارية العربية والسويدية والدولية",
      ctaTitle: "هل لديك سؤال أو اقتراح؟",
      ctaSubtitle: "نسعد بتواصلك معنا لأي استفسار أو اقتراح لتحسين الموقع.",
      ctaButton: "تواصل معنا",
    },
    en: {
      badge: "About Us",
      title: "ArabiSmart News",
      subtitle: "A smart news platform aggregating the most important Arabic, Swedish, and international news in one place, with AI-generated daily summaries.",
      missionTitle: "Our Mission",
      missionP1: "ArabiSmart News was founded to provide a comprehensive news experience for the Arabic community in Sweden and around the world. We believe that accurate information at the right time is a right for everyone.",
      missionP2: "We aggregate news from over 20 trusted sources and use AI to generate accurate daily summaries that save your time and keep you informed.",
      featuresTitle: "What Sets Us Apart",
      sourcesTitle: "Our News Sources",
      sourcesSubtitle: "We aggregate news from the most prominent Arabic, Swedish, and international sources",
      ctaTitle: "Have a question or suggestion?",
      ctaSubtitle: "We'd love to hear from you for any inquiries or suggestions to improve the site.",
      ctaButton: "Contact Us",
    },
    sv: {
      badge: "Om oss",
      title: "ArabiSmart News",
      subtitle: "En smart nyhetsplattform som samlar de viktigaste arabiska, svenska och internationella nyheterna på ett ställe, med AI-genererade dagliga sammanfattningar.",
      missionTitle: "Vårt uppdrag",
      missionP1: "ArabiSmart News grundades för att ge en heltäckande nyhetsupplevelse för den arabiska gemenskapen i Sverige och världen. Vi tror att korrekt information i rätt tid är en rättighet för alla.",
      missionP2: "Vi samlar nyheter från över 20 betrodda källor och använder AI för att generera korrekta dagliga sammanfattningar som sparar din tid.",
      featuresTitle: "Vad skiljer oss åt",
      sourcesTitle: "Våra nyhetskällor",
      sourcesSubtitle: "Vi samlar nyheter från de mest framstående arabiska, svenska och internationella källorna",
      ctaTitle: "Har du en fråga eller ett förslag?",
      ctaSubtitle: "Vi hör gärna från dig för eventuella frågor eller förslag för att förbättra sajten.",
      ctaButton: "Kontakta oss",
    },
  };

  const h = heroTexts[lang];
  const f = features[lang];
  const s = stats[lang];

  return (
    <div className="min-h-screen bg-background text-foreground" dir={t.dir}>
      <SEOHead
        title={h.title}
        description={h.subtitle}
        url="/about"
      />
      {/* Header */}
      <header className="border-b bg-background/95 backdrop-blur sticky top-0 z-50">
        <div className="container flex items-center justify-between h-14">
          <Link href="/">
            <div className="flex items-center gap-2 cursor-pointer">
              <Globe className="h-6 w-6 text-primary" />
              <span className="font-bold text-lg">ArabiSmart News</span>
            </div>
          </Link>
          <nav className="flex items-center gap-4 text-sm">
            <Link href="/"><span className="text-muted-foreground hover:text-foreground cursor-pointer transition-colors">{t.home}</span></Link>
            <Link href="/contact"><span className="text-muted-foreground hover:text-foreground cursor-pointer transition-colors">{t.contact}</span></Link>
            <Link href="/privacy"><span className="text-muted-foreground hover:text-foreground cursor-pointer transition-colors">{t.privacy}</span></Link>
            <LanguageSwitcher />
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-16 bg-gradient-to-b from-primary/10 to-background">
        <div className="container text-center space-y-6 max-w-3xl mx-auto">
          <Badge variant="outline">{h.badge}</Badge>
          <h1 className="text-4xl font-bold leading-tight">{h.title}</h1>
          <p className="text-xl text-muted-foreground leading-relaxed">{h.subtitle}</p>
        </div>
      </section>

      {/* Mission Section */}
      <section className="py-14 container max-w-4xl mx-auto">
        <div className="grid md:grid-cols-2 gap-8 items-center">
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">{h.missionTitle}</h2>
            <p className="text-muted-foreground leading-relaxed">{h.missionP1}</p>
            <p className="text-muted-foreground leading-relaxed">{h.missionP2}</p>
          </div>
          <div className="grid grid-cols-2 gap-4">
            {s.map((stat, i) => (
              <Card key={i} className="text-center p-4">
                <CardContent className="pt-2 space-y-2">
                  <div className="text-3xl font-bold text-primary">{stat.value}</div>
                  <p className="text-sm text-muted-foreground">{stat.label}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-14 bg-muted/30">
        <div className="container max-w-4xl mx-auto">
          <h2 className="text-2xl font-bold text-center mb-10">{h.featuresTitle}</h2>
          <div className="grid md:grid-cols-3 gap-6">
            {f.map((feature, i) => (
              <Card key={i} className="p-6 space-y-3">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                  {feature.icon}
                </div>
                <h3 className="font-semibold">{feature.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{feature.desc}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Sources Section */}
      <section className="py-14 container max-w-4xl mx-auto">
        <h2 className="text-2xl font-bold text-center mb-4">{h.sourcesTitle}</h2>
        <p className="text-center text-muted-foreground mb-8">{h.sourcesSubtitle}</p>
        <div className="flex flex-wrap justify-center gap-3">
          {["روسيا اليوم (RT Arabic)", "الجزيرة", "BBC Arabic", "العربية", "الكومبس", "SVT", "Aftonbladet", "الوطن", "سبوتنيك عربي", "دويتشه فيله"].map((source) => (
            <Badge key={source} variant="secondary" className="text-sm py-1 px-3">
              {source}
            </Badge>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-14 bg-primary/5 border-t border-b">
        <div className="container max-w-2xl mx-auto text-center space-y-6">
          <h2 className="text-2xl font-bold">{h.ctaTitle}</h2>
          <p className="text-muted-foreground">{h.ctaSubtitle}</p>
          <Link href="/contact">
            <Button size="lg" className="gap-2">
              <Mail className="h-4 w-4" />
              {h.ctaButton}
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t py-8 bg-muted/30">
        <div className="container text-center space-y-4">
          <div className="flex items-center justify-center gap-2">
            <Globe className="h-5 w-5 text-primary" />
            <p className="text-sm font-medium">ArabiSmart News - {t.siteSlogan}</p>
          </div>
          <div className="flex items-center justify-center gap-4 text-sm text-muted-foreground">
            <Link href="/privacy"><span className="hover:text-foreground cursor-pointer transition-colors">{t.privacy}</span></Link>
            <span>•</span>
            <Link href="/contact"><span className="hover:text-foreground cursor-pointer transition-colors">{t.contact}</span></Link>
            <span>•</span>
            <Link href="/about"><span className="hover:text-foreground cursor-pointer transition-colors">{t.about}</span></Link>
          </div>
          <p className="text-sm text-muted-foreground">© 2026 ArabiSmart News. {t.allRightsReserved}.</p>
        </div>
      </footer>
      <ScrollToTop />
    </div>
  );
}
