import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Sparkles,
  TrendingUp,
  Newspaper,
  Calendar,
  Loader2,
  RefreshCw,
  Trash2,
  Clock,
  BarChart3,
  Globe,
  Download,
  MessageCircle,
  Share2,
  Mail,
  Copy,
  Check,
  Zap,
  AlertTriangle,
} from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";

// ─── Types ────────────────────────────────────────────────────────────────────
type SummaryStats = {
  totalNews?: number;
  activeSources?: number;
  arabicNews?: number;
  swedishNews?: number;
};

type Summary = {
  id: number;
  date: Date | string;
  summary: string;
  topNews: number[];
  trendingTopics: string[];
  statistics: SummaryStats;
  language: string;
  createdAt: Date | string;
};

// ─── PDF Generator ────────────────────────────────────────────────────────────
function generatePDF(summary: Summary) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = margin;

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageW, 45, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("ArabiSmart News", pageW / 2, 18, { align: "center" });
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text("Daily AI Summary", pageW / 2, 27, { align: "center" });
  const dateStr = new Date(summary.date).toLocaleDateString("ar-SA", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });
  doc.setFontSize(10);
  doc.setTextColor(203, 213, 225);
  doc.text(dateStr, pageW / 2, 36, { align: "center" });
  y = 58;

  const stats = summary.statistics || {};
  const statItems = [
    { label: "Total News", value: stats.totalNews || 0 },
    { label: "Sources", value: stats.activeSources || 0 },
    { label: "Arabic", value: stats.arabicNews || 0 },
    { label: "Swedish", value: stats.swedishNews || 0 },
  ];
  const boxW = contentW / 4;
  statItems.forEach((s, i) => {
    const x = margin + i * boxW;
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(x + 1, y, boxW - 2, 18, 2, 2, "F");
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(String(s.value), x + boxW / 2, y + 8, { align: "center" });
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(s.label, x + boxW / 2, y + 14, { align: "center" });
  });
  y += 26;

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("Daily Summary", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  const summaryLines = doc.splitTextToSize(summary.summary, contentW);
  summaryLines.forEach((line: string) => {
    if (y > pageH - 30) { doc.addPage(); y = margin; }
    doc.text(line, margin, y);
    y += 5.5;
  });
  y += 6;

  if (summary.trendingTopics?.length > 0) {
    if (y > pageH - 40) { doc.addPage(); y = margin; }
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text("Trending Topics", margin, y);
    y += 7;
    let topicX = margin;
    summary.trendingTopics.forEach((topic) => {
      const tw = doc.getTextWidth(topic) + 8;
      if (topicX + tw > pageW - margin) { topicX = margin; y += 9; }
      doc.setFillColor(219, 234, 254);
      doc.roundedRect(topicX, y - 5, tw, 7, 1.5, 1.5, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(30, 64, 175);
      doc.text(topic, topicX + 4, y);
      topicX += tw + 3;
    });
    y += 14;
  }

  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageH - 14, pageW, 14, "F");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by ArabiSmart News | ${window.location.origin}`, pageW / 2, pageH - 5, { align: "center" });

  return doc;
}

// ─── Share Buttons ────────────────────────────────────────────────────────────
function ShareButtons({ summary }: { summary: Summary }) {
  const [copied, setCopied] = useState(false);
  const pageUrl = `${window.location.origin}/daily-summary`;
  const shareText = `📰 ملخص أخبار اليوم من ArabiSmart News\n\n${summary.summary.slice(0, 300)}...\n\n🔗 ${pageUrl}`;

  const handleDownloadPDF = () => {
    try {
      const doc = generatePDF(summary);
      const dateStr = new Date(summary.date).toISOString().split("T")[0];
      doc.save(`arabismart-daily-summary-${dateStr}.pdf`);
      toast.success("تم تحميل ملف PDF بنجاح!");
    } catch {
      toast.error("فشل تحميل PDF.");
    }
  };

  const handleWhatsApp = () => window.open(`https://wa.me/?text=${encodeURIComponent(shareText)}`, "_blank");
  const handleTelegram = () => window.open(`https://t.me/share/url?url=${encodeURIComponent(pageUrl)}&text=${encodeURIComponent(summary.summary.slice(0, 200))}`, "_blank");
  const handleEmail = () => {
    const subject = encodeURIComponent(`ملخص أخبار ${new Date(summary.date).toLocaleDateString("ar-SA")}`);
    const body = encodeURIComponent(shareText);
    window.open(`mailto:?subject=${subject}&body=${body}`, "_blank");
  };
  const handleCopy = async () => {
    await navigator.clipboard.writeText(shareText);
    setCopied(true);
    toast.success("تم نسخ الملخص!");
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-wrap gap-2">
      <Button onClick={handleDownloadPDF} size="sm" className="gap-1.5 bg-red-600 hover:bg-red-700 text-white rounded-full px-4">
        <Download className="w-3.5 h-3.5" /> PDF
      </Button>
      <Button onClick={handleWhatsApp} size="sm" className="gap-1.5 bg-green-600 hover:bg-green-700 text-white rounded-full px-4">
        <MessageCircle className="w-3.5 h-3.5" /> واتساب
      </Button>
      <Button onClick={handleTelegram} size="sm" className="gap-1.5 bg-blue-500 hover:bg-blue-600 text-white rounded-full px-4">
        <Share2 className="w-3.5 h-3.5" /> تيليجرام
      </Button>
      <Button onClick={handleEmail} size="sm" variant="outline" className="gap-1.5 rounded-full px-4">
        <Mail className="w-3.5 h-3.5" /> إيميل
      </Button>
      <Button onClick={handleCopy} size="sm" variant="outline" className="gap-1.5 rounded-full px-4">
        {copied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
        {copied ? "تم!" : "نسخ"}
      </Button>
    </div>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────
export default function AdminDailySummary() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState<number | null>(null);

  const utils = trpc.useUtils();

  const { data: summaries, isLoading } = trpc.dailySummary.list.useQuery();

  const generateMutation = trpc.dailySummary.generate.useMutation({
    onSuccess: () => {
      toast.success("تم توليد الملخص اليومي بنجاح!");
      utils.dailySummary.list.invalidate();
      utils.dailySummary.getLatest.invalidate();
      setIsGenerating(false);
    },
    onError: (error) => {
      toast.error(`فشل توليد الملخص: ${error.message}`);
      setIsGenerating(false);
    },
  });

  const deleteMutation = trpc.dailySummary.delete.useMutation({
    onSuccess: () => {
      toast.success("تم حذف الملخص بنجاح!");
      utils.dailySummary.list.invalidate();
      utils.dailySummary.getLatest.invalidate();
      setDeleteConfirm(null);
    },
    onError: (error) => {
      toast.error(`فشل الحذف: ${error.message}`);
    },
  });

  const handleGenerate = () => {
    setIsGenerating(true);
    generateMutation.mutate({ language: "ar" });
  };

  const handleDelete = (id: number) => {
    if (deleteConfirm === id) {
      deleteMutation.mutate({ id });
    } else {
      setDeleteConfirm(id);
      setTimeout(() => setDeleteConfirm(null), 3000);
    }
  };

  return (
    <div className="space-y-6" dir="rtl">
      {/* ── Header ── */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-blue-500" />
            إدارة الملخص اليومي
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            توليد وإدارة ملخصات الأخبار اليومية بالذكاء الاصطناعي
          </p>
        </div>
        <Button
          onClick={handleGenerate}
          disabled={isGenerating}
          className="gap-2 bg-gradient-to-l from-blue-600 to-indigo-600 text-white rounded-xl shadow-lg shadow-blue-600/20"
        >
          {isGenerating ? (
            <><Loader2 className="w-4 h-4 animate-spin" /> جاري التوليد...</>
          ) : (
            <><RefreshCw className="w-4 h-4" /> توليد ملخص جديد</>
          )}
        </Button>
      </div>

      {/* ── Schedule Info ── */}
      <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-4 flex items-center gap-3">
        <div className="w-9 h-9 rounded-xl bg-blue-500/10 flex items-center justify-center flex-shrink-0">
          <Clock className="w-5 h-5 text-blue-500" />
        </div>
        <div>
          <p className="text-sm font-medium">جدولة تلقائية مفعّلة</p>
          <p className="text-xs text-muted-foreground">يتم توليد الملخص تلقائياً كل يوم الساعة 7:00 صباحاً</p>
        </div>
        <Badge className="mr-auto bg-green-500/10 text-green-600 border-green-500/20 text-xs">
          <Zap className="w-3 h-3 ml-1" />
          نشط
        </Badge>
      </div>

      {/* ── Summaries List ── */}
      {isLoading ? (
        <div className="space-y-4">
          {[...Array(3)].map((_, i) => (
            <Skeleton key={i} className="h-48 rounded-2xl" />
          ))}
        </div>
      ) : !summaries || summaries.length === 0 ? (
        <div className="text-center py-16 rounded-2xl border border-dashed border-border">
          <div className="w-16 h-16 rounded-2xl bg-muted flex items-center justify-center mx-auto mb-4">
            <Sparkles className="w-8 h-8 text-muted-foreground" />
          </div>
          <h3 className="font-semibold text-lg mb-2">لا توجد ملخصات بعد</h3>
          <p className="text-sm text-muted-foreground mb-6">
            اضغط على "توليد ملخص جديد" لإنشاء أول ملخص يومي
          </p>
          <Button onClick={handleGenerate} disabled={isGenerating} className="gap-2">
            {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            توليد الملخص الآن
          </Button>
        </div>
      ) : (
        <div className="space-y-4">
          {summaries.map((s) => {
            const stats = (s.statistics as SummaryStats) || {};
            const isDeleting = deleteMutation.isPending && deleteConfirm === s.id;
            return (
              <div
                key={s.id}
                className="rounded-2xl border border-border bg-card shadow-sm overflow-hidden"
              >
                {/* Card Header */}
                <div className="flex items-center justify-between gap-4 px-6 py-4 border-b border-border bg-muted/30">
                  <div className="flex items-center gap-3">
                    <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center">
                      <Sparkles className="w-4 h-4 text-white" />
                    </div>
                    <div>
                      <p className="font-semibold text-sm">
                        {new Date(s.date).toLocaleDateString("ar-SA", {
                          weekday: "long",
                          year: "numeric",
                          month: "long",
                          day: "numeric",
                        })}
                      </p>
                      <p className="text-xs text-muted-foreground flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        تم الإنشاء: {new Date(s.createdAt).toLocaleTimeString("ar-SA")}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant="secondary" className="text-xs">
                      {s.language === "ar" ? "عربي" : s.language === "sv" ? "سويدي" : s.language}
                    </Badge>
                    <Button
                      onClick={() => handleDelete(s.id)}
                      disabled={isDeleting}
                      variant={deleteConfirm === s.id ? "destructive" : "ghost"}
                      size="sm"
                      className="gap-1.5 text-xs rounded-lg"
                    >
                      {isDeleting ? (
                        <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      ) : deleteConfirm === s.id ? (
                        <><AlertTriangle className="w-3.5 h-3.5" /> تأكيد الحذف</>
                      ) : (
                        <><Trash2 className="w-3.5 h-3.5" /> حذف</>
                      )}
                    </Button>
                  </div>
                </div>

                {/* Stats Row */}
                <div className="grid grid-cols-4 divide-x divide-x-reverse divide-border border-b border-border">
                  {[
                    { icon: Newspaper, label: "أخبار", value: stats.totalNews || 0 },
                    { icon: Globe, label: "مصادر", value: stats.activeSources || 0 },
                    { icon: BarChart3, label: "عربي", value: stats.arabicNews || 0 },
                    { icon: Calendar, label: "سويدي", value: stats.swedishNews || 0 },
                  ].map((item, i) => (
                    <div key={i} className="flex flex-col items-center justify-center py-3 gap-0.5">
                      <item.icon className="w-4 h-4 text-muted-foreground mb-1" />
                      <span className="text-lg font-bold">{item.value}</span>
                      <span className="text-xs text-muted-foreground">{item.label}</span>
                    </div>
                  ))}
                </div>

                {/* Summary Text */}
                <div className="px-6 py-4">
                  <p className="text-sm leading-[1.9] text-muted-foreground line-clamp-4 text-right">
                    {s.summary}
                  </p>
                </div>

                {/* Trending Topics */}
                {s.trendingTopics?.length > 0 && (
                  <div className="px-6 pb-3">
                    <div className="flex items-center gap-2 mb-2">
                      <TrendingUp className="w-3.5 h-3.5 text-muted-foreground" />
                      <span className="text-xs text-muted-foreground font-medium">الموضوعات الرائجة:</span>
                    </div>
                    <div className="flex flex-wrap gap-1.5">
                      {s.trendingTopics.map((topic: string, i: number) => (
                        <span
                          key={i}
                          className="text-xs px-2.5 py-1 rounded-full bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/20"
                        >
                          {topic}
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                {/* Share Bar */}
                <div className="px-6 py-3 border-t border-border bg-muted/20 flex items-center justify-between flex-wrap gap-3">
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <Share2 className="w-3.5 h-3.5" />
                    مشاركة
                  </span>
                  <ShareButtons summary={s as Summary} />
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
